### ISSUE TITLE
Testing Module incompatible versions

### ISSUE THREAD

**Issue by sankalpmukim** [7codeRO/nest-prisma-rest-api-boilerplate#7]
## The Problem

The repository uses **^9.1.4** for most nest packages including Core and Common. But it uses **^7.6.13** for testing.

```ts
import { Test, TestingModule } from '@nestjs/testing';

import { AppController } from './app.controller';
import { AppService } from './app.service';

describe('AppController', () => {
  let _app: TestingModule;

  beforeAll(async () => {
    _app = await Test.createTestingModule({
      controllers: [AppController],
      providers: [AppService],
    }).compile();
  });
});
```

I was doing some simple unit testing on `app.controller.spec.ts` and got this error:
![image](https://user-images.githubusercontent.com/41541375/222960270-49a66b7a-d983-4d93-a906-0ddf7faac19d.png)

This causes all tests to fail.

## Recommendation

We need to upgrade the testing module to the compatible correct version.
^9.1.4

**Comment by sankalpmukim** [comment]
I have tested it working with the correct version and I'm willing to make a PR. Please assign this issue to me.

PS: I love this Nest - Prisma boilerplate. It is perfect.

**Comment by sankalpmukim** [comment]
Also, I'm not super familiar with what could be the downfall/cost to change but I wanna suggest switching to Vitest instead of jest. Since I've already opened this issue, I thought we can use this to discuss.

**Comment by GarryOne** [comment]
Hi, @sankalpmukim. Thanks for opening this issue. I didn't use `Vitest` so far, it would cost nothing to switch to it, but we should see if it applies better to all of us, I mean to the est of community. 

For such decisions, I'd look at resources like https://2022.stateofjs.com/en-US/libraries/testing/

Jest: 
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/6481499/223122378-29420f8a-c74c-41ec-a9b0-fbce860af272.png">

Vitest:
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/6481499/223122401-5594a4c7-3bd4-4249-9511-19b890bc1a05.png">

Considering that, if the last year, `Jest` had a bit of decrease, while `Vitest` had a bit of increase, I think it would be ok for such as switch.

**Comment by sankalpmukim** [comment]
Another other issue I faced was how to mock prisma properly. I looked up a lot of different ways and a combination of Nest and Prisma's official documentation plus stackoverflow came to the rescue.

Maybe we should document it / provide a structured documentation for it.

References:

https://stackoverflow.com/a/72443811/12446525
https://docs.nestjs.com/fundamentals/testing#testing
https://www.prisma.io/docs/guides/testing/unit-testing

Also, sorry for starting a discussion on what was supposed to be an actual issue. Should we title this issue "testing discussion" and open the original bug in a separate issue?

**Comment by GarryOne** [comment]
No. I think it's fine to keep the discussion here, on this `issue`. The repo and activity is not that big to make sense splitting between issues and discussions.

**Comment by sankalpmukim** [comment]
Okay.
I love this template a lot and intend to use it in the future as well. Please assign this issue to me because I'd love to be a contributor to this repo!

**Comment by GarryOne** [comment]
Done. Assigned it to you. Feel free to open a PR :) 
Thanks for contribution!

**Comment by GarryOne** [comment]
https://github.com/7codeRO/nest-prisma-rest-api-boilerplate/pull/8
